### PR TITLE
Check for missing web modules in dev mode and fix them

### LINKED ISSUE #10: Adding a new dependency when running dev mode fails
So if you start svelvet in dev mode and then at any point you add a **new unique node_modules import path**, you'll likely get a runtime error saying that file doesn't exist. The other possibility is that you already had that module installed, but you're referencing a *different* path for the first time. 

This happens because svelvet runs `snowpack` **only once** and we don't track (watch) your source for new import paths. 

### Workarounds

Any time you install a new dependency and import it somewhere in your src, **always restart dev mode**.

### Long-term

It looks like we'll have to track all your import paths in order for svelvet to understand when to run `snowpack` again. This shouldn't be difficult... it's just a bit of extra overhead that we'll have to live with.

### PR DESCRIPTION
**Pull request by jakedeichert**
### Which issue does this fix?

Closes #10 

### Describe the solution

This fixes the issue where a user is running svelvet in dev mode and imports a new path that snowpack didn't see before and therefore hasn't generated into a web_module yet.

This checks for new non-relative and non-absolute import paths and then triggers snowpack again when it finds one.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -149,9 +150,31 @@ async function minify(destPath: string): Promise<void> {
...
+        const importPath = source.substring(meta.s, meta.e);
+        const notRelative = !importPath.startsWith('.');
+        const notAbsolute = !importPath.startsWith('/');
+        // Must be a node_module that snowpack didn't see before
+        return notRelative && notAbsolute;
+    });
+
+    if (foundMissingWebModule) {
+        await snowpack();
+    }
```
Comment (jakedeichert) [inline src/index.ts]: So this currently doesn't work and I'll explain why!

The gist of this is that when snowpack runs a **second time** on the dist directory with `--include 'dist/**/*'`, it crashes with this error: 

```js
Failed to build with snowpack
- snowpack installing... 
⠼ snowpack installing... svelte, svelte/internal.js
✖ Cannot find module 'svelte/internal.js'
Require stack:
- /Users/jake/svelvet/node_modules/snowpack/dist-node/index.js
- /Users/jake/svelvet/node_modules/snowpack/dist-node/index.bin.js
⚠ Finished with warnings.
```

This seems to be caused by the `.js` extension the babel transform step adds.

On the **first run** of snowpack, it sees this and correctly generates `web_modules`: 

```js
import { onMount } from "svelte/internal";
```

But, on the **second run** of snowpack, it sees this and then crashes:

```js
// babel transform step has ran and snowpack can't resolve "svelte/internal.js"
import { onMount } from "/web_modules/svelte/internal.js";
```

Notably, I tested removing the `.js` extension like below, and snowpack correctly generates `web_modules` and doesn't crash:

```js
import { onMount } from "/web_modules/svelte/internal";
```

@FredKSchott does this seem like a bug? Should snowpack handle both cases `svelte/internal` and `/web_modules/svelte/internal.js` ?

The `import-map.json` looks like this:

```json
{
  "imports": {
    "svelte/internal": "./svelte/internal.js"
  }
}
```

So my guess is that snowpack isn't using this file to understand that `./svelte/internal.js` is actually the same as `svelte/internal`. 🤔

Comment (jakedeichert) [reply src/index.ts]: So I have an alternative solution that I'm going to implement here for now due to this snowpack issue. Instead of just running snowpack a second time on the dist directory (which is ideal), I'm going to restart the dev mode process from a clean state (delete dist dir and rebuild as if we just started dev mode for the first time).

This is much slower compared to the ideal solution which is adjusting snowpack to not crash / handle gracefully when it sees `/web_modules/svelte/internal.js` for example.

Comment (jakedeichert) [reply src/index.ts]: Solved this in a better way. https://github.com/jakedeichert/svelvet/pull/52/files#diff-f41e9d04a45c83f3b6f6e630f10117feR133-R135

Running `snowpack --include 'changed/file.js'` before babel transforms are applied. This way snowpack doesn't crash and it's way faster than starting from a clean slate.
